async def async_error_mock(*_):
    raise Exception("mock error")


async def error_mock(*_):
    raise Exception("mock error")
